### PR TITLE
Support Leiningen 2

### PR DESCRIPTION
**Pull request by technomancy**
Would be nice to cut a non-snapshot release too.

### CODE REVIEW

**Comment by aphyr** [comment]
+1 to this.

**Comment by travis** [comment]
yow, not sure how I missed this! will take a look, merge, cut non-snapshot. thanks!!

**Comment by travis** [comment]
clearly did not do this. this pr still good? I have not used lein-deb in a long time...

**Comment by travis** [comment]
ok after chatting with @technomancy I'ma close this

**Pull request closed without merging**
